version: '3.8'

services:
  terravision_app:
    build:
      context: ../../..
      dockerfile: src/main/docker/terravision_gpu.dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../../../.env_docker_gpu
    volumes:
      - ../../../:/app
    working_dir: /app

    gpus:
      - driver: nvidia
        count: all
        capabilities: [compute, utility, video]
